# iris 데이터분석

## SVC model

In [4]:
import pandas as pd
import numpy as np
import pickle

In [5]:
?pickle

In [9]:
df = pd.read_csv('iris.data')
# csv_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
col_names = ['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width','Species']
# df =  pd.read_csv(csv_url, names = col_names)
df =  pd.read_csv('iris.data', names = col_names)
df[:]

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width         Species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [142]:
# print(df.head())
# print(df.tail())
# print(df.dtypes)

In [14]:
X = np.array(df.iloc[:, 0:4])
y = np.array(df.iloc[:, 4:])
print(y.shape)
# y[:]

(150, 1)


In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y.shape)
print(y[:])

(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [149]:
y.shape

(150,)

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [23]:
print("X_train: ==========================")
print(X_train)
print("X_test: ==========================")
print(X_test)
print("y_train : ==========================")
print(y_train)
print("y_test : ==========================")
print(y_test)


X_train: ==========================
[[5.2 4.1 1.5 0.1]
 [5.1 3.8 1.9 0.4]
 [6.4 2.8 5.6 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 3.1 1.5 0.1]
 [7.  3.2 4.7 1.4]
 [4.8 3.  1.4 0.3]
 [6.9 3.1 5.4 2.1]
 [5.1 3.8 1.5 0.3]
 [5.1 3.4 1.5 0.2]
 [6.2 2.9 4.3 1.3]
 [5.8 2.6 4.  1.2]
 [6.1 3.  4.6 1.4]
 [4.6 3.4 1.4 0.3]
 [5.6 2.9 3.6 1.3]
 [6.4 3.2 4.5 1.5]
 [6.7 3.  5.  1.7]
 [4.9 2.5 4.5 1.7]
 [4.9 3.1 1.5 0.1]
 [5.9 3.2 4.8 1.8]
 [6.3 2.9 5.6 1.8]
 [5.8 4.  1.2 0.2]
 [5.2 3.4 1.4 0.2]
 [5.1 3.7 1.5 0.4]
 [5.  3.5 1.6 0.6]
 [6.7 2.5 5.8 1.8]
 [6.2 3.4 5.4 2.3]
 [5.5 2.3 4.  1.3]
 [4.6 3.6 1.  0.2]
 [6.5 3.  5.2 2. ]
 [4.7 3.2 1.3 0.2]
 [6.7 3.  5.2 2.3]
 [4.3 3.  1.1 0.1]
 [4.8 3.4 1.9 0.2]
 [4.4 3.  1.3 0.2]
 [6.1 2.9 4.7 1.4]
 [5.7 2.5 5.  2. ]
 [4.9 3.1 1.5 0.1]
 [7.3 2.9 6.3 1.8]
 [4.6 3.2 1.4 0.2]
 [6.9 3.1 5.1 2.3]
 [5.  2.  3.5 1. ]
 [6.4 2.9 4.3 1.3]
 [5.6 3.  4.5 1.5]
 [4.9 2.4 3.3 1. ]
 [5.8 2.7 5.1 1.9]
 [6.  3.  4.8 1.8]
 [5.4 3.4 1.5 0.4]
 [5.7 3.  4.2 1.2]
 [4.8 3.  1.4 0.1]
 [5.8 2.7 5.1 

In [26]:
# ?X_train

In [28]:
from sklearn.svm import SVC
sv = SVC(kernel='linear').fit(X_train,y_train)

In [29]:
?sv

In [36]:
arr = np.array([[6.7, 3.0, 5.2,  2.3]])
pred = sv.predict(arr)
pred[0]
print(pred[:])

[2]


In [40]:
pred = sv.predict(X_test)
print(pred[:])

[2 2 2 2 2 2 1 1 2 2 2 0 2 0 2 1 0 0 1 0 0 1 0 2 0 1 2 1 0 2]


In [33]:
?pred

In [30]:
pickle.dump(sv, open('iris.pkl', 'wb'))

In [41]:
import pickle
import numpy as np

model = pickle.load(open('iris.pkl', 'rb'))
arr = np.array([[ 5.1, 3.5, 1.4, 0.2]])
pred = model.predict(arr)
pred[0]
print(pred[0])

arr = np.array([[6.7, 3.0, 5.2,  2.3]])
pred = model.predict(arr)
pred[0]
print(pred[0])

arr = np.array([[5.5, 2.4, 3.8, 1.1]])
pred = model.predict(arr)
pred[0]
print(pred[0])

0
2
1


# 플라스크 백엔드 코드


In [166]:
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello():
    return 'hello kdata class'

In [168]:
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello():
    return 'hello kdata class'

@app.route('/about')
def about():
    return 'Kdata class <br> from seoultech university'
        
@app.route('/contact')
def contact():
    return 'tel : 012-345-6789'

In [169]:
from flask import Flask
from markupsafe import escape

app = Flask(__name__)

@app.route("/<name>")
def hello(name):
    return f"Hello, {escape(name)}!"

In [170]:
from flask import Flask, render_template, request
import pickle
import numpy as np

model = pickle.load(open('iris.pkl', 'rb'))

app = Flask(__name__)



@app.route('/')
def man():
    return render_template('home.html')


@app.route('/predict', methods=['POST'])
def home():
    data1 = request.form['a']
    data2 = request.form['b']
    data3 = request.form['c']
    data4 = request.form['d']
    arr = np.array([[data1, data2, data3, data4]])
    pred = model.predict(arr)
    return render_template('after.html', data=pred)


if __name__ == "__main__":
    app.run(debug=True)


 * Serving Flask app '__main__'
 * Debug mode: on


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with watchdog (windowsapi)


SystemExit: 1

C:\ProgramData\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3468: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [174]:
# iris.py
import pandas as pd
import numpy as np
import pickle

df = pd.read_csv('iris.data')

X = np.array(df.iloc[:, 0:4])
y = np.array(df.iloc[:, 4:])

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.svm import SVC
sv = SVC(kernel='linear').fit(X_train,y_train)


pickle.dump(sv, open('iri.pkl', 'wb'))


C:\ProgramData\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [2]:
# after.html

<html>
<body bgcolor=#a3cfb4>
    <center>
        <h1>  PREDICTION :  </h1>
    
    {%if data == 0%}
    <h1>Iris-setosa</h1>  
    <img src='static\setosa.jpg'>  
    {%elif data == 1%}
    <h1>Iris-virginica</h1>  
    <img src='static\flower1.jpg'>  
    {%else%}
    <h1>Iris-versicolor</h1>
    <img src='static\verci.jpg'>
    {%endif%}
        <br><br>
    <a href='/'>go back to home page</a>
    </center>
</body>
</html>

SyntaxError: invalid syntax (772602451.py, line 3)

In [3]:
# home.html

<html>
    <body bgcolor=#d4a3ae>
        <center>
        <h1> IRIS FLOWER DETECTION </h1><br>
        
        <form method="POST", action="{{url_for('home')}}">
           <b> First value :  <input type="text", name='a', placeholder="enter 1"> <br><br>
            Second value :  <input type="text", name='b', placeholder="enter 2"> <br><br>
            Third value :  <input type="text", name='c', placeholder="enter 3"> <br><br>
            Fourth value : <input type="text", name='d', placeholder="enter 4"> <br><br><br></b>
            <input type="submit" , value='predict!' >
        </form>

        <img src='static\flower1.jpg' alt="flower">
        </center>
    </body>
</html>


SyntaxError: invalid syntax (4135303507.py, line 3)